// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3BEnalx3tGj0IuFv6Oj0nuj9tlaMpTRk',
    appId: '1:442964636518:web:ac1389ec484d3bddd18ea7',
    messagingSenderId: '442964636518',
    projectId: 'mob3-uas-022-endah-a7435',
    authDomain: 'mob3-uas-022-endah-a7435.firebaseapp.com',
    storageBucket: 'mob3-uas-022-endah-a7435.firebasestorage.app',
    measurementId: 'G-KREEDM6ZS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2cV9sKh0SRQq5wf7aZWCT2nMrSwPFoZY',
    appId: '1:442964636518:android:2a3cd24cb49527d4d18ea7',
    messagingSenderId: '442964636518',
    projectId: 'mob3-uas-022-endah-a7435',
    storageBucket: 'mob3-uas-022-endah-a7435.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtPumImx7aGMfx3Wwnx4Kzp6WNl5oNYtY',
    appId: '1:442964636518:ios:d6936c65abcd4359d18ea7',
    messagingSenderId: '442964636518',
    projectId: 'mob3-uas-022-endah-a7435',
    storageBucket: 'mob3-uas-022-endah-a7435.firebasestorage.app',
    iosBundleId: 'com.example.mob3Login022Endah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3BEnalx3tGj0IuFv6Oj0nuj9tlaMpTRk',
    appId: '1:442964636518:web:3ffd806554fc0ab8d18ea7',
    messagingSenderId: '442964636518',
    projectId: 'mob3-uas-022-endah-a7435',
    authDomain: 'mob3-uas-022-endah-a7435.firebaseapp.com',
    storageBucket: 'mob3-uas-022-endah-a7435.firebasestorage.app',
    measurementId: 'G-DJBXCDYSWS',
  );
}
